add user controller and item controller
ihiwblby/java-shareit pull request #2
Opened 2024-12-17 20:28 UTC by ihiwblby

2024-12-18 18:12 UTC, z8q requested changes

2024-12-18 18:12 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return UserMapper.toUserDto(user);
можно немного оптимизировать
```JAVA
return userRepository.getById(id)
        .map(UserMapper::toUserDto)
        .orElseThrow(() -> new NotFoundException("Пользователь не найден"));
```
у Optional есть свой метод map, он будет выполняться при непустом Optional,
при пустом будет бросаться исключение

2024-12-18 18:12 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        }
чтобы не делать однотипные проверки,
можно в методах контроллера добавить валидацию аргумента
```JAVA
getById(@Positive @PathVariable Long id)
```

но нужно будет еще над классом контроллера поставить `@Validated`, чтобы Positive заработала
стоит потестировать

2024-12-18 18:12 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dao/UserRepositoryImpl.java
> +        return users.values();
если возвращать так - return new ArrayList(users.values)
то в возвращаемом типе вместо Collection можно будет поставить List

2024-12-19 07:02 UTC, ihiwblby commented
Узнала, что есть метод StringUtils.isBlank()
Добавила его в search() и update() в классе ItemRepositoryImpl

2024-12-19 20:15 UTC, z8q approved these changes

2024-12-20 08:34 UTC, merged